apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: my-local-storage
  hostPath:
    path: /tmp/data
# you can rerplace the host path option with required cloud providers like
# after capacity and storage
# for aws
# awsElasticBLockStora:
#   volumeID: <volume-id>
#   fsType: ext4
